version: '3'
services:
  server:
    build: server/
    ports:
    - "1234:1234"
  client:
    build: client/
    command: "hello from docker-compose"
    network_mode: host
    depends_on: 
      - server
